draw_set_alpha(0.5)
draw_set_color(c_black)
draw_rectangle(0, 0, room_width, room_height, false)
draw_self()
draw_set_alpha(1)
draw_sprite(s_witch_bowl, 0, (room_width / 2), (room_height / 2))
draw_set_color(c_white)
draw_set_font(fnt_wave)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text(x, y, (string((global.wave_no + 1)) + "º ONDA"))
draw_set_halign(fa_left)
